### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by tomasbw** [intel/safestringlib#15]
commit 961c6084a527b2e163d4129f1a80792b6e7f849

gcc -c -o objtest/test_memcmp16_s.o unittests/test_memcmp16_s.c -Iinclude -fstack-protector-strong -fPIE -fPIC -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security
In file included from include/safe_lib.h:59:0,
                 from include/safe_mem_lib.h:36,
                 from unittests/test_memcmp16_s.c:8:
include/safe_str_lib.h:268:8: error: unknown type name ‘wchar_t’
 extern wchar_t *
        ^~~~~~~
include/safe_str_lib.h:269:10: error: unknown type name ‘wchar_t’; did you mean ‘__gwchar_t’?
 wcpcpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src, errno_t *err);
          ^~~~~~~
          __gwchar_t
include/safe_str_lib.h:269:45: error: unknown type name ‘wchar_t’
 wcpcpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src, errno_t *err);
                                             ^~~~~~~
include/safe_str_lib.h:273:10: error: unknown type name ‘wchar_t’; did you mean ‘__gwchar_t’?
 wcscat_s(wchar_t* dest, rsize_t dmax, const wchar_t* src);
          ^~~~~~~
          __gwchar_t
include/safe_str_lib.h:273:45: error: unknown type name ‘wchar_t’
 wcscat_s(wchar_t* dest, rsize_t dmax, const wchar_t* src);
                                             ^~~~~~~
include/safe_str_lib.h:277:11: error: unknown type name ‘wchar_t’; did you mean ‘__gwchar_t’?
 wcsncat_s(wchar_t *dest, rsize_t dmax, const wchar_t *src, rsize_t slen);
           ^~~~~~~
           __gwchar_t
include/safe_str_lib.h:277:46: error: unknown type name ‘wchar_t’
 wcsncat_s(wchar_t *dest, rsize_t dmax, const wchar_t *src, rsize_t slen);
                                              ^~~~~~~
include/safe_str_lib.h:281:10: error: unknown type name ‘wchar_t’; did you mean ‘__gwchar_t’?
 wcscpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src);
          ^~~~~~~
          __gwchar_t
include/safe_str_lib.h:281:45: error: unknown type name ‘wchar_t’
 wcscpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src);
                                             ^~~~~~~
include/safe_str_lib.h:285:11: error: unknown type name ‘wchar_t’; did you mean ‘__gwchar_t’?
 wcsncpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src, rsize_t slen);
           ^~~~~~~
           __gwchar_t
include/safe_str_lib.h:285:46: error: unknown type name ‘wchar_t’
 wcsncpy_s(wchar_t* dest, rsize_t dmax, const wchar_t* src, rsize_t slen);
                                              ^~~~~~~
include/safe_str_lib.h:289:17: error: unknown type name ‘wchar_t’
 wcsnlen_s(const wchar_t *dest, rsize_t dmax);
                 ^~~~~~~
make: *** [makefile:47: objtest/test_memcmp16_s.o] Error 1

**Comment by dmwheel1** [comment]
Tomas,
Can you please provide the gcc version you are using?
Thanks,
Dave

**Comment by tomasbw** [comment]
gcc (GCC) 7.2.1  but the code just missing  include to <wchar.h>

Author: Tomas Winkler <tomas.winkler@intel.com>
Date:   Tue Feb 6 20:45:20 2018 +0200

    safestringlib: add missing include to wchar.h

    fix compilation error because of missing include
    to wchar.h

    Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>

diff --git a/include/safe_str_lib.h b/include/safe_str_lib.h
index 597d7203c96b..e50df36d9fbb 100644
--- a/include/safe_str_lib.h
+++ b/include/safe_str_lib.h
@@ -33,6 +33,7 @@
 #define __SAFE_STR_LIB_H__

 #include "safe_lib.h"
+#include <wchar.h>

**Comment by dmwheel1** [comment]
Fixed in pull request #17
