### ISSUE TITLE
Please consider library versioning with releases or stable branches

### ISSUE THREAD

**Issue by stgrzeszczak** [intel/safestringlib#16]
Hi,

I'm a member of a project, which uses your library. Our build scripts used to download the source code 
[from github](https://github.com/intel/safestringlib/archive/master.zip)
for compilation.
This is problematic for two reasons. We want to verify the archive file's integrity using a checksum. However, the zip file changes with every commit, so the checksum changes too, so the checks fail.
Secondly, whenever a recent commit [causes compilation problems](https://github.com/intel/safestringlib/issues/15), this is a problem for us too, because we have to patch the library on our side.

Could you please consider either using github releases to provide library snapshots with versions (eg, safestringlib 1.0, 1.1), or moving development to another branch, which would be merged to the master branch after the changes are complete, tested and verified?

**Comment by dmwheel1** [comment]
Added branch for v1.0.0 on last stable master commit.
Will add branches and releases from now on.

**Comment by stgrzeszczak** [comment]
Thank you!
