### ISSUE TITLE
uint8_t pointers

### ISSUE THREAD

**Issue by kloetzl** [intel/safestringlib#19]
At multiple places throughout the library, `uint8_t*` is used to access bytes of memory (See [here](https://github.com/intel/safestringlib/blob/master/safeclib/memcmp_s.c#L94), [here](https://github.com/intel/safestringlib/blob/ce7bc0092d94b626532859a0c5cfcfae782f50a1/safeclib/mem_primitives_lib.c#L79), …). However, this is invalid as by section 6.2.5 of the C11 standard only `char` and variants thereof are considered *character types,* enjoying the privilege of being able to point to any object of any type. Thus, the implemented practice is technically undefined behavior.

**Comment by dmwheel1** [comment]
uint8_t * is a typedef to an unsigned char, so according to your rational there is no issue. I am closing this as not an issue. If you feel that is unwarranted, please repost a new issue and include the error message this is causing for a particular platform or compiler.
