### ISSUE TITLE
Several API Reference Links not Working (e.g. memcpy_s)

### ISSUE THREAD

**Issue by posborne** [intel/safestringlib#20]
Looks like the Wiki formatting is off a touch for links like this one: https://github.com/intel/safestringlib/wiki/API-Reference#name-memcpy_s.  Looks like the markdown might just be a touch off.

I was following these links from https://github.com/intel/safestringlib/wiki/SDL-List-of-Banned-Functions

**Comment by dmwheel1** [comment]
Found and fixed severl NAME reference links that were missing spaces between the ### NAME
