### ISSUE TITLE
Autoconf Support

### ISSUE THREAD

**Issue by ware** [intel/safestringlib#25]
The makefile is brittle when it comes to platform independence.  We should really use something like autoconf to make the builds more flexible.  I'll put something together and submit a pull request.

**Comment by dmwheel1** [comment]
I've created a branch called automake that generates the makefile from
autoconf
./configure
and allows the configure to include flags that define what gets added to the library.
The template make file allows easy changes to increase/decrease those included functions

Have a look. I still have some compiler issues to address (for -Wall) in the unittest directory, and I need to update the  configure.ac to properly construct the list of elements in the unittest from the list of configured functions.

**Comment by tomasbw** [comment]
switching to cmake, should provide the multi platform support.
