### ISSUE TITLE
Modular Build

### ISSUE THREAD

**Issue by ware** [intel/safestringlib#26]
Once support for more flexible builds is put in place (like autoconf) we should put in place the ability to select which functions are compiled in.

**Comment by tomasbw** [comment]
What is the rational behind this request?

**Comment by ware** [comment]
We've had requests from people who only want to use specific functions from this library but then to use similar functions from elsewhere.  Additionally, some people want their code as small as possible so want the library to only include the functions that they use.

**Comment by tomasbw** [comment]
We added a pull request that adds build by cmake and enable partial builds via cmake option mechaism.

**Comment by dmwheel1** [comment]
I've created a build system from autotools.
Which is a better system? CMake vs autotools?

**Comment by tomasbw** [comment]
We are using the safestringlib on multiple OSes,  as far as I know autotools are not filling that part, they are unix oriented.

**Comment by dmwheel1** [comment]
Tomas, you added CMake – is that the preferred solution for your cross-platform compilation?

**Comment by tomasbw** [comment]
Resolved using cmake.
