### ISSUE TITLE
documentation enhancement request

### ISSUE THREAD

**Issue by fenrus75** [intel/safestringlib#5]
Would be great if the documentation would explain how this is more or less secure than normal linux software using -fstack-protector and FORTIFY_SOURCE, and please also document if and how this library enhances rather than replaces FORTIFY_SOURCE ?

**Comment by dmwheel1** [comment]
Please see new Wiki page here
https://github.com/intel/safestringlib/wiki/FORTIFY-SOURCE-and-Safe-String-Library

**Comment by fenrus75** [comment]
unfortunately that is rather unsatisfactory

I wish it had said "and we use the same underlying building blocks to make the library even more safe"

**Comment by dmwheel1** [comment]
Could you say more about what you mean, and what you are looking for? We aren't doing the same thing as FORTIFY SOURCE, so I am a bit confused by your comment. What building blocks are you hoping to see in common?

**Comment by fenrus75** [comment]
I would love to read "we are also using the same __builtin_object_size()
mechanism to additionally use the information the compiler can give us to
make the code even more secrure"
