### ISSUE TITLE
Length guard in strisdigit_s not implemented

### ISSUE THREAD

**Issue by Wee-Free-Scot** [intel/safestringlib#54]
In function `strisdigit_s`, the `dmax` value is decremented in the per-character loop, but its value is never checked, so the loop carries on past the intended max length until it finds a null char, which is exactly the behaviour it exists to prevent.

Suggested fix: something like `if (dmax<=0) break` between lines 108 and 109 (if the output should be `true`).

**Comment by tomasbw** [comment]
Fixed by  #64
